---
- name: Install packages
  apt:
    pkg: "{{ apt_packages_install }}"
    state: present
    update_cache: yes

- name: Uninstall packages
  apt:
    pkg: "{{ apt_packages_uninstall }}"
    state: absent
