---
- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ apt_packages_install }}"

- name: Uninstall packages
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items: "{{ apt_packages_uninstall }}"
