---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: deb8
    image: debian:8
    privileged: yes
  - name: deb9
    image: debian:9
    privileged: yes
  - name: deb10
    image: debian:10
    privileged: yes
  - name: ubu12
    image: ubuntu:12.04
    privileged: yes
  - name: ubu14
    image: ubuntu:14.04
    privileged: yes
  - name: ubu16
    image: ubuntu:16.04
    privileged: yes
  - name: ubu18
    image: ubuntu:18.04
    privileged: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
