---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: debian:8
    privileged: yes
  - name: instance
    image: debian:9
    privileged: yes
  - name: instance
    image: ubuntu:12.04
    privileged: yes
  - name: instance
    image: ubuntu:14.04
    privileged: yes
  - name: instance
    image: ubuntu:16.04
    privileged: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
